title: Schilings's Knowledge Base
description: 大模型训练与推理技术笔记
baseurl: /assets
theme: null
liquid:
  error_mode: warn
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
  syntax_highlighter: rouge
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
